[env:m5stick-cplus]
platform = espressif32@6.9.0
board = m5stick-c
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbserial-*
upload_speed = 115200
board_build.filesystem = spiffs
board_build.partitions = default.csv

lib_deps =
    m5stack/M5StickCPlus@^0.1.0
    bblanchon/ArduinoJson@^7.0.0

build_flags =
    -DARDUINO_M5STICK_C_PLUS
    -D CORE_DEBUG_LEVEL=1
